/**
 * Kuratierte Liste der wichtigsten Kreuzfahrt-Häfen weltweit mit Koordinaten.
 * Für die Karten-Darstellung im Surroundings-Tab.
 *
 * Quelle: UN/LOCODE + IMO Port-Liste, manuell auf die größten Embarkation-Häfen
 * reduziert. Erweiterung über das Backend (`server/src/data/cities.ts`
 * CRUISE_PORTS) möglich — dort fehlen aktuell nur die Lat/Lng.
 */
import type { Coord } from "./mockData";

export interface CruisePortPin {
  code: string;
  name: string;
  city: string;
  country: string;
  coord: Coord;
}

export const CRUISE_PORT_PINS: CruisePortPin[] = [
  // === Mittelmeer ===
  { code: "PORT-CIV", name: "Civitavecchia (Rom)", city: "Civitavecchia", country: "Italy", coord: { latitude: 42.0942, longitude: 11.7956 } },
  { code: "PORT-BCN", name: "Barcelona", city: "Barcelona", country: "Spain", coord: { latitude: 41.3500, longitude: 2.1660 } },
  { code: "PORT-VEN", name: "Venedig", city: "Venezia", country: "Italy", coord: { latitude: 45.4407, longitude: 12.3155 } },
  { code: "PORT-PIR", name: "Piräus (Athen)", city: "Piraeus", country: "Greece", coord: { latitude: 37.9420, longitude: 23.6477 } },
  { code: "PORT-MAR", name: "Marseille", city: "Marseille", country: "France", coord: { latitude: 43.3463, longitude: 5.3092 } },
  { code: "PORT-NAP", name: "Neapel", city: "Napoli", country: "Italy", coord: { latitude: 40.8420, longitude: 14.2570 } },
  { code: "PORT-PMI", name: "Palma de Mallorca", city: "Palma", country: "Spain", coord: { latitude: 39.5572, longitude: 2.6280 } },
  { code: "PORT-DBV", name: "Dubrovnik", city: "Dubrovnik", country: "Croatia", coord: { latitude: 42.6611, longitude: 18.0838 } },
  { code: "PORT-SPU", name: "Split", city: "Split", country: "Croatia", coord: { latitude: 43.5045, longitude: 16.4422 } },
  { code: "PORT-LIV", name: "Livorno (Florenz)", city: "Livorno", country: "Italy", coord: { latitude: 43.5523, longitude: 10.3015 } },
  { code: "PORT-VAL", name: "Valencia", city: "Valencia", country: "Spain", coord: { latitude: 39.4456, longitude: -0.3194 } },
  { code: "PORT-MLA", name: "Valletta (Malta)", city: "Valletta", country: "Malta", coord: { latitude: 35.8989, longitude: 14.5146 } },
  { code: "PORT-GEN", name: "Genua", city: "Genova", country: "Italy", coord: { latitude: 44.4080, longitude: 8.9282 } },
  { code: "PORT-AJC", name: "Ajaccio (Korsika)", city: "Ajaccio", country: "France", coord: { latitude: 41.9192, longitude: 8.7388 } },
  { code: "PORT-MON", name: "Monaco / Monte Carlo", city: "Monaco", country: "Monaco", coord: { latitude: 43.7386, longitude: 7.4250 } },
  { code: "PORT-NCE", name: "Nice", city: "Nice", country: "France", coord: { latitude: 43.7039, longitude: 7.2747 } },
  { code: "PORT-MLG", name: "Málaga", city: "Málaga", country: "Spain", coord: { latitude: 36.7099, longitude: -4.4153 } },
  { code: "PORT-CAD", name: "Cádiz", city: "Cádiz", country: "Spain", coord: { latitude: 36.5347, longitude: -6.2956 } },
  { code: "PORT-LIS", name: "Lissabon", city: "Lisboa", country: "Portugal", coord: { latitude: 38.7065, longitude: -9.1356 } },
  { code: "PORT-FNC", name: "Funchal (Madeira)", city: "Funchal", country: "Portugal", coord: { latitude: 32.6450, longitude: -16.9079 } },
  { code: "PORT-TFS", name: "Santa Cruz de Tenerife", city: "Tenerife", country: "Spain", coord: { latitude: 28.4796, longitude: -16.2376 } },
  { code: "PORT-LPA", name: "Las Palmas (Gran Canaria)", city: "Las Palmas", country: "Spain", coord: { latitude: 28.1466, longitude: -15.4111 } },
  { code: "PORT-PMO", name: "Palermo", city: "Palermo", country: "Italy", coord: { latitude: 38.1377, longitude: 13.3672 } },
  { code: "PORT-CTA", name: "Catania", city: "Catania", country: "Italy", coord: { latitude: 37.4985, longitude: 15.0903 } },
  { code: "PORT-IST", name: "Istanbul (Galataport)", city: "Istanbul", country: "Turkey", coord: { latitude: 41.0246, longitude: 28.9849 } },
  { code: "PORT-JTR", name: "Santorini", city: "Santorini", country: "Greece", coord: { latitude: 36.4163, longitude: 25.4321 } },
  { code: "PORT-JMK", name: "Mykonos", city: "Mykonos", country: "Greece", coord: { latitude: 37.4467, longitude: 25.3289 } },
  { code: "PORT-RHO", name: "Rhodos", city: "Rhodos", country: "Greece", coord: { latitude: 36.4471, longitude: 28.2310 } },
  { code: "PORT-CFU", name: "Korfu", city: "Korfu", country: "Greece", coord: { latitude: 39.6230, longitude: 19.9163 } },

  // === Nordeuropa ===
  { code: "PORT-CPH", name: "Kopenhagen", city: "København", country: "Denmark", coord: { latitude: 55.6987, longitude: 12.5995 } },
  { code: "PORT-STO", name: "Stockholm", city: "Stockholm", country: "Sweden", coord: { latitude: 59.3299, longitude: 18.0762 } },
  { code: "PORT-HEL", name: "Helsinki", city: "Helsinki", country: "Finland", coord: { latitude: 60.1505, longitude: 24.9486 } },
  { code: "PORT-OSL", name: "Oslo", city: "Oslo", country: "Norway", coord: { latitude: 59.9091, longitude: 10.7434 } },
  { code: "PORT-BGO", name: "Bergen", city: "Bergen", country: "Norway", coord: { latitude: 60.3990, longitude: 5.3144 } },
  { code: "PORT-TRD", name: "Trondheim", city: "Trondheim", country: "Norway", coord: { latitude: 63.4435, longitude: 10.3994 } },
  { code: "PORT-TRO", name: "Tromsø", city: "Tromsø", country: "Norway", coord: { latitude: 69.6492, longitude: 18.9553 } },
  { code: "PORT-GEI", name: "Geiranger", city: "Geiranger", country: "Norway", coord: { latitude: 62.1010, longitude: 7.2050 } },
  { code: "PORT-HAM", name: "Hamburg", city: "Hamburg", country: "Germany", coord: { latitude: 53.5447, longitude: 9.9684 } },
  { code: "PORT-KIE", name: "Kiel", city: "Kiel", country: "Germany", coord: { latitude: 54.3168, longitude: 10.1300 } },
  { code: "PORT-WAR", name: "Warnemünde (Rostock)", city: "Warnemünde", country: "Germany", coord: { latitude: 54.1798, longitude: 12.0815 } },
  { code: "PORT-AMS", name: "Amsterdam", city: "Amsterdam", country: "Netherlands", coord: { latitude: 52.3884, longitude: 4.8920 } },
  { code: "PORT-RTM", name: "Rotterdam", city: "Rotterdam", country: "Netherlands", coord: { latitude: 51.9047, longitude: 4.4839 } },
  { code: "PORT-SOU", name: "Southampton", city: "Southampton", country: "United Kingdom", coord: { latitude: 50.8973, longitude: -1.4034 } },
  { code: "PORT-DOV", name: "Dover", city: "Dover", country: "United Kingdom", coord: { latitude: 51.1239, longitude: 1.3275 } },
  { code: "PORT-REY", name: "Reykjavík", city: "Reykjavík", country: "Iceland", coord: { latitude: 64.1500, longitude: -21.9333 } },
  { code: "PORT-TLL", name: "Tallinn", city: "Tallinn", country: "Estonia", coord: { latitude: 59.4444, longitude: 24.7536 } },
  { code: "PORT-RIX", name: "Riga", city: "Riga", country: "Latvia", coord: { latitude: 56.9505, longitude: 24.1051 } },
  { code: "PORT-GDN", name: "Gdańsk", city: "Gdańsk", country: "Poland", coord: { latitude: 54.4070, longitude: 18.6648 } },

  // === Caribbean / Americas ===
  { code: "PORT-MIA", name: "Miami", city: "Miami", country: "United States", coord: { latitude: 25.7785, longitude: -80.1798 } },
  { code: "PORT-FLL", name: "Fort Lauderdale (Port Everglades)", city: "Fort Lauderdale", country: "United States", coord: { latitude: 26.0915, longitude: -80.1163 } },
  { code: "PORT-PCN", name: "Port Canaveral", city: "Port Canaveral", country: "United States", coord: { latitude: 28.4083, longitude: -80.6258 } },
  { code: "PORT-GAL", name: "Galveston", city: "Galveston", country: "United States", coord: { latitude: 29.3107, longitude: -94.7818 } },
  { code: "PORT-NYC", name: "New York", city: "New York", country: "United States", coord: { latitude: 40.7706, longitude: -74.0058 } },
  { code: "PORT-NAS", name: "Nassau (Bahamas)", city: "Nassau", country: "Bahamas", coord: { latitude: 25.0816, longitude: -77.3375 } },
  { code: "PORT-COZ", name: "Cozumel", city: "Cozumel", country: "Mexico", coord: { latitude: 20.5067, longitude: -86.9456 } },
  { code: "PORT-SJU", name: "San Juan", city: "San Juan", country: "Puerto Rico", coord: { latitude: 18.4655, longitude: -66.1057 } },
  { code: "PORT-LAX", name: "Los Angeles (San Pedro)", city: "Los Angeles", country: "United States", coord: { latitude: 33.7405, longitude: -118.2724 } },
  { code: "PORT-SEA", name: "Seattle", city: "Seattle", country: "United States", coord: { latitude: 47.6157, longitude: -122.3409 } },
  { code: "PORT-VAN", name: "Vancouver", city: "Vancouver", country: "Canada", coord: { latitude: 49.2889, longitude: -123.1117 } },
  { code: "PORT-GCM", name: "George Town (Cayman)", city: "George Town", country: "Cayman Islands", coord: { latitude: 19.2925, longitude: -81.3852 } },
  { code: "PORT-BTC", name: "Bridgetown (Barbados)", city: "Bridgetown", country: "Barbados", coord: { latitude: 13.1037, longitude: -59.6303 } },
  { code: "PORT-RIO", name: "Rio de Janeiro", city: "Rio de Janeiro", country: "Brazil", coord: { latitude: -22.8956, longitude: -43.1736 } },
  { code: "PORT-BUE", name: "Buenos Aires", city: "Buenos Aires", country: "Argentina", coord: { latitude: -34.5946, longitude: -58.3717 } },

  // === Asien / Pazifik ===
  { code: "PORT-SIN", name: "Singapore (Marina Bay)", city: "Singapore", country: "Singapore", coord: { latitude: 1.2643, longitude: 103.8451 } },
  { code: "PORT-HKG", name: "Hong Kong (Kai Tak)", city: "Hong Kong", country: "Hong Kong", coord: { latitude: 22.3168, longitude: 114.2098 } },
  { code: "PORT-DXB", name: "Dubai (Mina Rashid)", city: "Dubai", country: "United Arab Emirates", coord: { latitude: 25.2700, longitude: 55.2780 } },
  { code: "PORT-SYD", name: "Sydney (Circular Quay)", city: "Sydney", country: "Australia", coord: { latitude: -33.8612, longitude: 151.2105 } },
  { code: "PORT-AKL", name: "Auckland", city: "Auckland", country: "New Zealand", coord: { latitude: -36.8410, longitude: 174.7672 } },
  { code: "PORT-YOK", name: "Yokohama", city: "Yokohama", country: "Japan", coord: { latitude: 35.4540, longitude: 139.6380 } },
  { code: "PORT-CPT", name: "Kapstadt", city: "Cape Town", country: "South Africa", coord: { latitude: -33.9028, longitude: 18.4321 } },

  // === Mittelmeer (zusätzlich) ===
  { code: "PORT-VLE", name: "Valletta Grand Harbour", city: "Valletta", country: "Malta", coord: { latitude: 35.8995, longitude: 14.5135 } },
  { code: "PORT-KOR", name: "Korčula", city: "Korčula", country: "Croatia", coord: { latitude: 42.9603, longitude: 17.1366 } },
  { code: "PORT-HVA", name: "Hvar", city: "Hvar", country: "Croatia", coord: { latitude: 43.1729, longitude: 16.4413 } },
  { code: "PORT-ZAD", name: "Zadar", city: "Zadar", country: "Croatia", coord: { latitude: 44.1186, longitude: 15.2287 } },
  { code: "PORT-PUL", name: "Pula", city: "Pula", country: "Croatia", coord: { latitude: 44.8666, longitude: 13.8496 } },
  { code: "PORT-KOT", name: "Kotor", city: "Kotor", country: "Montenegro", coord: { latitude: 42.4247, longitude: 18.7712 } },
  { code: "PORT-DUR", name: "Durrës", city: "Durrës", country: "Albania", coord: { latitude: 41.3128, longitude: 19.4533 } },
  { code: "PORT-BAR", name: "Bari", city: "Bari", country: "Italy", coord: { latitude: 41.1382, longitude: 16.8540 } },
  { code: "PORT-BRR", name: "Brindisi", city: "Brindisi", country: "Italy", coord: { latitude: 40.6485, longitude: 17.9621 } },
  { code: "PORT-OLB", name: "Olbia", city: "Olbia", country: "Italy", coord: { latitude: 40.9241, longitude: 9.4985 } },
  { code: "PORT-CAG", name: "Cagliari", city: "Cagliari", country: "Italy", coord: { latitude: 39.2099, longitude: 9.1234 } },
  { code: "PORT-SAL", name: "Salerno", city: "Salerno", country: "Italy", coord: { latitude: 40.6822, longitude: 14.7611 } },
  { code: "PORT-MES", name: "Messina", city: "Messina", country: "Italy", coord: { latitude: 38.1933, longitude: 15.5544 } },
  { code: "PORT-TPS", name: "Trapani", city: "Trapani", country: "Italy", coord: { latitude: 38.0163, longitude: 12.5097 } },
  { code: "PORT-LIT", name: "La Spezia", city: "La Spezia", country: "Italy", coord: { latitude: 44.1024, longitude: 9.8275 } },
  { code: "PORT-PVK", name: "Korfu (Kerkyra)", city: "Korfu", country: "Greece", coord: { latitude: 39.6243, longitude: 19.9217 } },
  { code: "PORT-KAT", name: "Katakolon", city: "Katakolon", country: "Greece", coord: { latitude: 37.6446, longitude: 21.3197 } },
  { code: "PORT-CHQ", name: "Chania (Souda)", city: "Chania", country: "Greece", coord: { latitude: 35.5039, longitude: 24.0750 } },
  { code: "PORT-HER", name: "Heraklion", city: "Heraklion", country: "Greece", coord: { latitude: 35.3417, longitude: 25.1530 } },
  { code: "PORT-VOL", name: "Volos", city: "Volos", country: "Greece", coord: { latitude: 39.3563, longitude: 22.9445 } },
  { code: "PORT-MYT", name: "Mytilini (Lesbos)", city: "Mytilini", country: "Greece", coord: { latitude: 39.1071, longitude: 26.5538 } },
  { code: "PORT-KUS", name: "Kuşadası", city: "Kuşadası", country: "Turkey", coord: { latitude: 37.8581, longitude: 27.2562 } },
  { code: "PORT-IZM", name: "İzmir", city: "İzmir", country: "Turkey", coord: { latitude: 38.4444, longitude: 27.1428 } },
  { code: "PORT-ANT", name: "Antalya", city: "Antalya", country: "Turkey", coord: { latitude: 36.8390, longitude: 30.6249 } },
  { code: "PORT-LIM", name: "Limassol", city: "Limassol", country: "Cyprus", coord: { latitude: 34.6494, longitude: 33.0410 } },
  { code: "PORT-HFA", name: "Haifa", city: "Haifa", country: "Israel", coord: { latitude: 32.8221, longitude: 35.0070 } },
  { code: "PORT-ALY", name: "Alexandria", city: "Alexandria", country: "Egypt", coord: { latitude: 31.1989, longitude: 29.8742 } },
  { code: "PORT-PSD", name: "Port Said", city: "Port Said", country: "Egypt", coord: { latitude: 31.2566, longitude: 32.2841 } },
  { code: "PORT-TNG", name: "Tanger", city: "Tanger", country: "Morocco", coord: { latitude: 35.7787, longitude: -5.8024 } },
  { code: "PORT-CMN", name: "Casablanca", city: "Casablanca", country: "Morocco", coord: { latitude: 33.6056, longitude: -7.6147 } },
  { code: "PORT-TUN", name: "Tunis (La Goulette)", city: "Tunis", country: "Tunisia", coord: { latitude: 36.8189, longitude: 10.3036 } },

  // === Nordeuropa (zusätzlich) ===
  { code: "PORT-LRV", name: "Larvik", city: "Larvik", country: "Norway", coord: { latitude: 59.0490, longitude: 10.0307 } },
  { code: "PORT-AND", name: "Ålesund", city: "Ålesund", country: "Norway", coord: { latitude: 62.4722, longitude: 6.1486 } },
  { code: "PORT-KSU", name: "Kristiansund", city: "Kristiansund", country: "Norway", coord: { latitude: 63.1131, longitude: 7.7332 } },
  { code: "PORT-MOL", name: "Molde", city: "Molde", country: "Norway", coord: { latitude: 62.7375, longitude: 7.1591 } },
  { code: "PORT-HMR", name: "Hammerfest", city: "Hammerfest", country: "Norway", coord: { latitude: 70.6634, longitude: 23.6821 } },
  { code: "PORT-LON", name: "Longyearbyen (Svalbard)", city: "Longyearbyen", country: "Norway", coord: { latitude: 78.2232, longitude: 15.6267 } },
  { code: "PORT-FAE", name: "Tórshavn (Faroe Islands)", city: "Tórshavn", country: "Denmark", coord: { latitude: 62.0080, longitude: -6.7724 } },
  { code: "PORT-VST", name: "Visby (Gotland)", city: "Visby", country: "Sweden", coord: { latitude: 57.6402, longitude: 18.2978 } },
  { code: "PORT-NYL", name: "Nynäshamn", city: "Nynäshamn", country: "Sweden", coord: { latitude: 58.9036, longitude: 17.9492 } },
  { code: "PORT-MHQ", name: "Mariehamn (Åland)", city: "Mariehamn", country: "Finland", coord: { latitude: 60.0974, longitude: 19.9348 } },
  { code: "PORT-RNN", name: "Rønne (Bornholm)", city: "Rønne", country: "Denmark", coord: { latitude: 55.0993, longitude: 14.7035 } },
  { code: "PORT-LBE", name: "Lübeck", city: "Lübeck", country: "Germany", coord: { latitude: 53.8945, longitude: 10.7026 } },
  { code: "PORT-BRH", name: "Bremerhaven", city: "Bremerhaven", country: "Germany", coord: { latitude: 53.5396, longitude: 8.5765 } },
  { code: "PORT-GBG", name: "Göteborg", city: "Göteborg", country: "Sweden", coord: { latitude: 57.7089, longitude: 11.9747 } },
  { code: "PORT-KAR", name: "Karlskrona", city: "Karlskrona", country: "Sweden", coord: { latitude: 56.1612, longitude: 15.5869 } },
  { code: "PORT-CRK", name: "Cork (Cobh)", city: "Cobh", country: "Ireland", coord: { latitude: 51.8514, longitude: -8.2941 } },
  { code: "PORT-BEL", name: "Belfast", city: "Belfast", country: "United Kingdom", coord: { latitude: 54.6238, longitude: -5.9092 } },
  { code: "PORT-GRE", name: "Greenock", city: "Greenock", country: "United Kingdom", coord: { latitude: 55.9485, longitude: -4.7659 } },
  { code: "PORT-INV", name: "Invergordon", city: "Invergordon", country: "United Kingdom", coord: { latitude: 57.6920, longitude: -4.1632 } },
  { code: "PORT-LPL", name: "Liverpool", city: "Liverpool", country: "United Kingdom", coord: { latitude: 53.4063, longitude: -2.9947 } },
  { code: "PORT-HAR", name: "Harwich", city: "Harwich", country: "United Kingdom", coord: { latitude: 51.9498, longitude: 1.2856 } },
  { code: "PORT-PMS", name: "Portsmouth", city: "Portsmouth", country: "United Kingdom", coord: { latitude: 50.8061, longitude: -1.1018 } },

  // === Karibik / Amerika (zusätzlich) ===
  { code: "PORT-PVR", name: "Puerto Vallarta", city: "Puerto Vallarta", country: "Mexico", coord: { latitude: 20.6595, longitude: -105.2371 } },
  { code: "PORT-CUN", name: "Cancún (Costa Maya)", city: "Costa Maya", country: "Mexico", coord: { latitude: 18.7382, longitude: -87.7022 } },
  { code: "PORT-MZT", name: "Mazatlán", city: "Mazatlán", country: "Mexico", coord: { latitude: 23.1907, longitude: -106.4234 } },
  { code: "PORT-PCY", name: "Panama City", city: "Panama City", country: "Panama", coord: { latitude: 8.9824, longitude: -79.5199 } },
  { code: "PORT-PHL", name: "Philipsburg (St. Maarten)", city: "Philipsburg", country: "Sint Maarten", coord: { latitude: 18.0181, longitude: -63.0535 } },
  { code: "PORT-FFE", name: "Fort-de-France (Martinique)", city: "Fort-de-France", country: "Martinique", coord: { latitude: 14.6042, longitude: -61.0676 } },
  { code: "PORT-PTP", name: "Pointe-à-Pitre (Guadeloupe)", city: "Pointe-à-Pitre", country: "Guadeloupe", coord: { latitude: 16.2410, longitude: -61.5286 } },
  { code: "PORT-CUR", name: "Willemstad (Curaçao)", city: "Willemstad", country: "Curaçao", coord: { latitude: 12.1091, longitude: -68.9322 } },
  { code: "PORT-ARU", name: "Oranjestad (Aruba)", city: "Oranjestad", country: "Aruba", coord: { latitude: 12.5246, longitude: -70.0353 } },
  // PORT-GCM existiert bereits in Caribbean-Sektion oben — kein Duplikat hier
  { code: "PORT-OBQ", name: "Ocho Rios (Jamaica)", city: "Ocho Rios", country: "Jamaica", coord: { latitude: 18.4072, longitude: -77.1031 } },
  { code: "PORT-MOB", name: "Montego Bay (Jamaica)", city: "Montego Bay", country: "Jamaica", coord: { latitude: 18.4747, longitude: -77.9203 } },
  { code: "PORT-LBD", name: "Labadee (Haiti)", city: "Labadee", country: "Haiti", coord: { latitude: 19.7000, longitude: -72.2333 } },
  { code: "PORT-PAP", name: "Punta Arenas", city: "Punta Arenas", country: "Chile", coord: { latitude: -53.1638, longitude: -70.9171 } },
  { code: "PORT-USH", name: "Ushuaia", city: "Ushuaia", country: "Argentina", coord: { latitude: -54.8089, longitude: -68.3030 } },
  { code: "PORT-SLO", name: "San Diego", city: "San Diego", country: "United States", coord: { latitude: 32.7185, longitude: -117.1727 } },
  { code: "PORT-SFO", name: "San Francisco", city: "San Francisco", country: "United States", coord: { latitude: 37.8055, longitude: -122.4196 } },
  { code: "PORT-PDX", name: "Astoria", city: "Astoria", country: "United States", coord: { latitude: 46.1879, longitude: -123.8313 } },
  { code: "PORT-JNU", name: "Juneau (Alaska)", city: "Juneau", country: "United States", coord: { latitude: 58.3019, longitude: -134.4197 } },
  { code: "PORT-SKW", name: "Skagway (Alaska)", city: "Skagway", country: "United States", coord: { latitude: 59.4583, longitude: -135.3139 } },
  { code: "PORT-KTN", name: "Ketchikan (Alaska)", city: "Ketchikan", country: "United States", coord: { latitude: 55.3422, longitude: -131.6461 } },

  // === Asien / Pazifik (zusätzlich) ===
  { code: "PORT-KOB", name: "Kobe", city: "Kobe", country: "Japan", coord: { latitude: 34.6824, longitude: 135.1996 } },
  { code: "PORT-OSK", name: "Osaka", city: "Osaka", country: "Japan", coord: { latitude: 34.6500, longitude: 135.4313 } },
  { code: "PORT-OKA", name: "Okinawa (Naha)", city: "Naha", country: "Japan", coord: { latitude: 26.2178, longitude: 127.6699 } },
  { code: "PORT-PUS", name: "Busan", city: "Busan", country: "South Korea", coord: { latitude: 35.0993, longitude: 129.0356 } },
  { code: "PORT-SHA", name: "Shanghai", city: "Shanghai", country: "China", coord: { latitude: 31.2317, longitude: 121.4737 } },
  { code: "PORT-CAN", name: "Guangzhou", city: "Guangzhou", country: "China", coord: { latitude: 23.0964, longitude: 113.3037 } },
  { code: "PORT-XIA", name: "Xiamen", city: "Xiamen", country: "China", coord: { latitude: 24.4632, longitude: 118.0830 } },
  { code: "PORT-TPE", name: "Keelung", city: "Keelung", country: "Taiwan", coord: { latitude: 25.1290, longitude: 121.7400 } },
  { code: "PORT-PHU", name: "Phuket", city: "Phuket", country: "Thailand", coord: { latitude: 7.8221, longitude: 98.3923 } },
  { code: "PORT-KUL", name: "Port Klang (Kuala Lumpur)", city: "Port Klang", country: "Malaysia", coord: { latitude: 3.0033, longitude: 101.3911 } },
  { code: "PORT-PEN", name: "Penang", city: "Penang", country: "Malaysia", coord: { latitude: 5.4141, longitude: 100.3370 } },
  { code: "PORT-DPS", name: "Benoa (Bali)", city: "Denpasar", country: "Indonesia", coord: { latitude: -8.7461, longitude: 115.2126 } },
  { code: "PORT-MNL", name: "Manila", city: "Manila", country: "Philippines", coord: { latitude: 14.5995, longitude: 120.9842 } },
  { code: "PORT-CHN", name: "Chennai", city: "Chennai", country: "India", coord: { latitude: 13.1004, longitude: 80.2913 } },
  { code: "PORT-COK", name: "Kochi", city: "Kochi", country: "India", coord: { latitude: 9.9618, longitude: 76.2592 } },
  { code: "PORT-MUS", name: "Muscat", city: "Muscat", country: "Oman", coord: { latitude: 23.6238, longitude: 58.5747 } },
  { code: "PORT-BHR", name: "Manama (Bahrain)", city: "Manama", country: "Bahrain", coord: { latitude: 26.2369, longitude: 50.5783 } },
  { code: "PORT-MEL", name: "Melbourne", city: "Melbourne", country: "Australia", coord: { latitude: -37.8420, longitude: 144.9220 } },
  { code: "PORT-BNE", name: "Brisbane", city: "Brisbane", country: "Australia", coord: { latitude: -27.3826, longitude: 153.1697 } },
  { code: "PORT-PER", name: "Fremantle (Perth)", city: "Fremantle", country: "Australia", coord: { latitude: -32.0566, longitude: 115.7424 } },
  { code: "PORT-CRC", name: "Cairns", city: "Cairns", country: "Australia", coord: { latitude: -16.9203, longitude: 145.7710 } },
  // PORT-AKL Auckland existiert bereits oben
  { code: "PORT-WLG", name: "Wellington", city: "Wellington", country: "New Zealand", coord: { latitude: -41.2784, longitude: 174.7795 } },
  { code: "PORT-MOM", name: "Mombasa", city: "Mombasa", country: "Kenya", coord: { latitude: -4.0436, longitude: 39.6682 } },
  { code: "PORT-ZNZ", name: "Stone Town (Sansibar)", city: "Stone Town", country: "Tanzania", coord: { latitude: -6.1632, longitude: 39.1880 } },
  { code: "PORT-MRU", name: "Port Louis (Mauritius)", city: "Port Louis", country: "Mauritius", coord: { latitude: -20.1601, longitude: 57.4990 } },
];
